services:
  - type: web
    name: api1
    plan: free
    branch: master
    env: docker
    dockerContext: src/CQRS.Api  # Add this line
    dockerfilePath: Dockerfile 

  - type: web
    name: api2
    plan: free
    branch: master
    env: docker
    dockerContext: src/Sample.Api  
    dockerfilePath: Dockerfile 
