services:
  - type: web
    name: cqrs-api
    plan: free
    branch: master
    env: docker
    dockerContext: src/CQRS.Api
    dockerfilePath: Dockerfile
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://*:8080

  - type: web
    name: sample-api
    plan: free
    branch: master
    env: docker
    dockerContext: src/Sample.Api
    dockerfilePath: Dockerfile
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://*:8081
