services:
  - type: web
    name: api1
    runtime: dotnet
    buildCommand: dotnet publish src/CQRS.Api/CQRS.Api.csproj -c Release -o ./publish
    startCommand: dotnet src/CQRS.Api/publish/CQRS.Api.dll
    env: dotnet
    autoDeploy: true
    branch: master

  - type: web
    name: api2
    runtime: dotnet
    buildCommand: dotnet publish src/Sample.Api/Sample.Api.csproj -c Release -o ./publish
    startCommand: dotnet src/Sample.Api/publish/Sample.Api.dll
    env: dotnet
    autoDeploy: true
    branch: master
