services:
  - type: web
    name: myapi
    env: docker
    plan: free                    
    autoDeploy: true              
    branch: master  
    repoPath: src/CQRS.Api

  - type: web
    name: myapi
    env: docker
    plan: free                    
    autoDeploy: true              
    branch: master  
    repoPath: src/Sample.Api
    
