services:
  - type: web
    name: myapi                   
    env: aspnetcore                
    plan: free                    
    autoDeploy: true              
    branch: master                  
    buildCommand: "dotnet build"  
    startCommand: "dotnet MyApi.dll" 
