services:
  - type: web
    name: myapi
    env: docker
    plan: free                    
    autoDeploy: true              
    branch: master                  
    buildCommand: "dotnet build src/CQRS.Api/CQRS.Api.csproj"  
