services:
  - type: web
    name: myapi
    env: docker
    plan: free                    
    autoDeploy: true              
    branch: master  
    dockerfile: src/CQRS.Api/Dockerfile
    dockerContext: src/CQRS.Api

  - type: web
    name: myapi
    env: docker
    plan: free                    
    autoDeploy: true              
    branch: master  
    dockerfile: src/Sample.Api/Dockerfile
    dockerContext: src/Sample.Api
    
