services:
  - type: web
    name: cqrs-api
    plan: free
    branch: master
    env: docker
    dockerfilePath: ./src/CQRS.Api/Dockerfile
    dockerContext: .
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
    healthCheckPath: /health

  - type: web
    name: sample-api
    plan: free
    branch: master
    env: docker
    dockerfilePath: ./src/Sample.Api/Dockerfile
    dockerContext: .
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
    healthCheckPath: /health
