services:
  - type: web
    name: api1
    plan: free
    branch: master
    env: docker
    dockerfilePath: src/CQRS.Api/Dockerfile

  - type: web
    name: api2
    plan: free
    branch: master
    env: docker
    dockerfilePath: src/Sample.Api/Dockerfile
